import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{ type: "autogenerated", dirName: "." }],

  // But you can create a sidebar manually

  tutorialSidebar: [
    "intro",
    "docusaurus-tutorial",
    {
      type: "category",
      label: "Neovim",
      collapsible: true,
      collapsed: false,
      link: {
        type: "generated-index",
        description:
          "A tutorial on configuring Neovim with Lua, highlighting the Lazy plugin manager and recommended plugins.",
      },
      items: [
        {
          type: "doc",
          id: "Neovim/nvim-config-with-lua",
          label: "Neovim Configuration with Lua",
        },
        { type: "doc", id: "Neovim/useful-vi-tips", label: "Useful Vi Tips" },
        {
          type: "doc",
          id: "Neovim/plugin-manager-lazy",
          label: "Plugin Manager - Lazy",
        },
        {
          type: "category",
          label: "Plugins",
          collapsible: true,
          collapsed: true,
          items: ["Neovim/Plugins/nvim-tree"],
        },
      ],
    },
  ],
};

export default sidebars;
// { type: "doc", id: "", label: "" },
/* {
          type: "category",
          label: "Plugins",
          items: ["Neovim/Plugins/nvim-tree"],
        }, */
